---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodeapppod
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeappcontainer
          image: shyamsankar146/hello
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - port: 8082
      targetPort: 8080
